# cloudbuild.yaml
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'europe-west1-docker.pkg.dev/odin-book-468211/odin-book/my-server-image',
    '--build-arg', 'DATABASE_URL=${_DATABASE_URL}',
    'server/'
  ]
images:
- 'europe-west1-docker.pkg.dev/odin-book-468211/odin-book/my-server-image'

# Reference the secret from Secret Manager
substitutions:
  _DATABASE_URL: 'projects/odin-book-468211/secrets/NEON_DATABASE_URL/versions/latest'

# This part tells Cloud Build to pull the value from Secret Manager
# rather than using it as a hardcoded string.
# Note: You'll also need to configure permissions for your
# Cloud Build service account to access Secret Manager.
secretEnv: ['DATABASE_URL']